### ISSUE TITLE
Crosstool-ng snapshot is too old for bash 5.x

### ISSUE THREAD

**Issue by gsmecher** [lucaceresoli/zynqmp-pmufw-builder#3]
See https://github.com/crosstool-ng/crosstool-ng/pull/1127

Thanks!

**Comment by gsmecher** [comment]
(Apologies for the silence, @lucaceresoli - I haven't had a chance to try this out yet. Should I take this off my mental to-do list?)

**Comment by lucaceresoli** [comment]
No problem @gsmecher, I had forgot about it as well.

The version now on master should work, I did build-test it at least. Should you have a chance to test it you're very welcome to report whether it works for you.

**Comment by gsmecher** [comment]
Great - I haven't had the time to try this on my K26. When I do, I'll drop a note in here.
